In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(
    r"C:\Users\infor\OneDrive\Desktop\Machine Learning\DataSets\Titanic-Dataset.csv"
)
df = df[["Age", "Pclass", "Fare", "Survived"]]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
X = df.drop(columns=["Survived"])
y = df["Survived"]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [6]:
X_train.head()

      Age  Pclass    Fare
199  24.0       2  13.000
129  45.0       3   6.975
90   29.0       3   8.050
230  35.0       1  83.475
126   NaN       3   7.750

In [7]:
knn = KNNImputer(n_neighbors=3, weights="distance")

X_train_transform = knn.fit_transform(X_train)
X_test_transformed = knn.transform(X_test)

In [8]:
pd.DataFrame(X_train_transform, columns=X_train.columns)

           Age  Pclass      Fare
0    24.000000     2.0   13.0000
1    45.000000     3.0    6.9750
2    29.000000     3.0    8.0500
3    35.000000     1.0   83.4750
4    29.666667     3.0    7.7500
..         ...     ...       ...
663  30.000000     3.0    8.6625
664  26.959410     3.0    8.7125
665  71.000000     1.0   49.5042
666  32.666667     1.0  221.7792
667  49.762895     1.0   25.9250

[668 rows x 3 columns]

In [9]:
lr = LogisticRegression()

lr.fit(X_train_transform, y_train)

y_pred = lr.predict(X_test_transformed)

accuracy_score(y_test, y_pred)

0.7219730941704036

In [10]:
# Comparison with mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [11]:
lr = LogisticRegression()

lr.fit(X_train_trf2, y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test, y_pred2)

0.7130044843049327